### ISSUE TITLE
Withdraw Waiuku (WI) NDB

### ISSUE THREAD

**Issue by dirtyformal** [vatSys/new-zealand-dataset#77]
This is a part of the wider changes as promulgated in [AIC 25 MAR 21](http://www.aip.net.nz/pdf/supplements/aic_25mar21.pdf). This is also related to the withdrawal of the Surrey (SY) NDB - (Issue Num TBC).

This amendment is due to be effective from **17 JUN 21** (AIRAC 2106).

**To-do List**

- [ ] Remove WINB from `Airspace.xml`, `NAVAID.xml`
- [ ] Add waypoint VINCE to `Airspace.xml`

**Enroute Procedure Changes**
Remove the following, with no replacement.

- [ ] H231 (RO-WINB)
- [ ] V317 (WINB - LENGU)
- [ ] H339 (HN VOR - WINB)
- [ ] WINB Holding Pattern

WINB will also be removed from the DAVEE, PEPPE, SCARY and NOBAR arrivals. I'm unsure at this stage whether or not WINB will be replaced by VINCE in these procedures, as the AIC is a little vague. The fact that VINCE is replacing the waypoint leads me to believe that the STAR procedures will remain the same, with VINCE instead of WINB.
