### ISSUE TITLE
Withdraw Surrey (SY) NDB

### ISSUE THREAD

**Issue by dirtyformal** [vatSys/new-zealand-dataset#78]
This is a part of the wider changes as promulgated in [AIC 25 MAR 21](http://www.aip.net.nz/pdf/supplements/aic_25mar21.pdf). This is also related to the withdrawal of the Waiuku (WI) NDB -  Issue #77.

As opposed to WINB, SYNB **will** not be replaced with a new waypoint.

This amendment is due to be effective from **17 JUN 21** (AIRAC 2106).

**To-do List**

- [ ] Remove SYNB from `Airspace.xml` and `NAVAID.xml`.

**Enroute Procedure Changes**
Remove the following, with no replacement.

- [ ] H173 (SYNB - POKOM)
- [ ] H301 (HN VOR - SYNB)
- [ ] H381 (TGNB - SYNB)
- [ ] H403 (RO VOR - SYNB - AA VOR)
- [ ] V443 (SYNB - EMRAG)
- [ ] ENR SYNB Holding Pattern

There are a large number of Ardmore (AR) procedure changes that will be captured under a separate issue (TBC).
