### ISSUE TITLE
AIRAC 2103 Master Issue

### ISSUE THREAD

**Issue by dirtyformal** [vatSys/new-zealand-dataset#86]
AIRAC 2103 is to be prepared on the VATNZ 'wip-airac' branch [located here](https://github.com/vatnz-dev/new-zealand-dataset/tree/airac-wip).

- [ ]  **Amend `CHANGELOG.md`**
- [ ]  **Amend `README.md`**
- [ ]  **Amend `Profile.xml`**
- [ ]  **Initiate auto-release**

**Comment by dirtyformal** [comment]
**Changes made** - 

- **(#75) ADS-B Sites**
- **(#85) QN Frequencies**
